name: Automation Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      - name: Build and Run Tests
        run: mvn clean test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/surefire-reports/
